### ISSUE TITLE
.ttf files don't seem to work in windows

### ISSUE THREAD

**Issue by flowchartsman** [flowchartsman/greybeard#1]
Perhaps related to one or more of the following:
- https://typedrawers.com/discussion/1117/windows-doesnt-use-bitmaps-embedded-in-ttf-otf-fontforge
- https://github.com/fontforge/fontforge/issues/2738

**Comment by zezic** [comment]
I also can't open TTF files provided with your repo on my Ubuntu Linux machine, but I can open TTF files which I able to generate from your FontForge sources.

**Comment by flowchartsman** [comment]
My only concern with doing that is whether or not the OS is using the bitmap strikes for the appropriate sizes or not.  Can you verify? Did you have to fake an outline or at least include one? If so, would you provide me the method you used to generate the font? I was generating it without outlines like so:

![generate font](https://user-images.githubusercontent.com/926884/50597278-e86d8e80-0e74-11e9-9468-b3a2eb5bfe55.png)

But that seems to be invalid.

**Comment by fatherofinvention** [comment]
Hello! Is it possible to get a working TTF for Windows? I would love to be able to use this font too (great work, BTW) but I too am getting an error when trying to the one from the repo.

**Comment by flowchartsman** [comment]
I would love to provide one, but unfortunately I don't know enough about either fontforge or the Windows font subsystems to figure it out.  Nor do I have a Windows machine to test on, hence the "help wanted" label.  If you could come up with a successful patch, it would be most appreciated!

**Comment by irigarae** [comment]
[This](http://www.electronicdissonance.com/2010/01/raster-fonts-in-visual-studio-2010.html) explanation solved it for me (but doing so manually is tedious).

**Comment by flowchartsman** [comment]
@irigarae awesome! I will see if I can add it into the build process somehow, though PRs are absolutely welcome if someone finds the time to make it work.

**Comment by irigarae** [comment]
Don't know anything about FontForge, I just followed those steps. In any
case I realized that the font worked for me on IntelliJ, which is where I
tested, but not on Terminal, or Sublime Text, so it might not solve it
entirely. Thank you in any case for Greybeard!

**Comment by irigarae** [comment]
Don't know anything about FontForge, I just followed those steps. In any case I realized that the font worked for me on IntelliJ, which is where I tested, but not on Terminal, or Sublime Text, so it might not solve it entirely. Thank you in any case for Greybeard!

**Comment by flowchartsman** [comment]
Everyone: I have switched to [Bits'N'Picas](https://github.com/kreativekorp/bitsnpicas) for building TTF files. Please test away and let me know if it works better! Make sure you select the correct point size and you'll probably benefit from tweaking line numbers in your text editors as well.  For example, using Greybeard 15px in vscode, I have my point size set to `15` and my line height to `1`

Sorry it took so long!

CC: @irigarae @fatherofinvention @zezic

**Comment by flowchartsman** [comment]
Testers report that the font looks crisp and unaliased! Closing for now! Feel free to reopen if you run into any issues!

**Comment by rhyses-pieces** [comment]
Hello! I want to first off thank you for sharing this font! I wanted to reopen this issue because I've noticed that whenever I attempt to serve the ttf file on a webpage, I get an error message saying that the font file itself is corrupt. I get other errors when I try to manually convert the ttf file through fontsquirrel's font-face generator. I would love to use this font on my website but I'm not sure what's going on. :(

![corrupt_font1](https://user-images.githubusercontent.com/10332868/186611816-ede2b14c-9c7e-45e5-a759-14f15d87ba30.png)

![corrupt_font2](https://user-images.githubusercontent.com/10332868/186611397-e0ca2657-9771-4197-9e5b-c4b50d6fda19.png)

**Comment by flowchartsman** [comment]
@rhyses-pieces I don't believe this is the right issue for this, unless you are somehow only observing this issue on Windows systems? Some cursory research indicates that this might just be because the files are .ttf, and these give browsers issues. Issue #4 already tracks adding WOFF2 files, but I haven't had the time to implement this yet. Perhaps one of the tools I mention there will give better results than fontsquirrel. I did a quick conversion of the 16px version, which I'll attach here. See if that works. If so, then I'll know it can be integrated into the build process.
[Greybeard-16px-WOFF2.zip](https://github.com/flowchartsman/greybeard/files/9426732/Greybeard-16px-WOFF2.zip)

**Comment by flowchartsman** [comment]
Also, please comment on issue #4 with your results. Thanks!
