### ISSUE TITLE
Differences between Ttyp0

### ISSUE THREAD

**Issue by heyitscassio** [flowchartsman/greybeard#3]
I tried the font out, but didn't find any differences between Ttyp0, there is any?

**Comment by flowchartsman** [comment]
Yes, I've made some minor modifications (the only one that I can recall offhand is the modification to the ugly `#` character in the bold version of size 18), but I believe there have been a few others. I'm only just recently returning to the font after some time away, and now that it's built properly into TTFs it's easier to use, and I expect I'll make some more modifications as time wears on.  Thanks for taking a look!
