### ISSUE TITLE
woff/2 support

### ISSUE THREAD

**Issue by flowchartsman** [flowchartsman/greybeard#4]
Consider woff/woff2 for web use. Shouldn't be too difficult with a little Makefile/Docker magic.

**Comment by flowchartsman** [comment]
Per comment in issue #1, .ttf files don't seem to embed well in browsers, so should investigate using fonttools or https://github.com/google/woff2 for automatic conversion in build, since Bits'N'Picas does not support woff/woff2 output.

**Comment by rhyses-pieces** [comment]
hi there! my apologies for posting in the wrong thread 😅 i just did a quick preliminary test as per #1 and it seems to be working now. many thanks!

**Comment by flowchartsman** [comment]
These files are now integrated into the new build process and are available in the [`dist/woff2`](https://github.com/flowchartsman/greybeard/tree/master/dist/woff2) directory. Thank you for your submission!
